using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using FieldTakHub.Builder.Models;

namespace FieldTakHub.Builder.Services;

public sealed record ProjectLayout(string RootDirectory, string SourceDirectory, string OutputDirectory, string ProjectFile);

public sealed class WorkspaceService
{
    public static readonly string[] SourceFolders = { "atak", "apps", "plugins", "maps", "overlays", "config", "data", "meshtastic", "enrollment" };

    public string DefaultProjectsRoot => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
        "FieldTAKHub", "Projects");

    public ProjectLayout EnsureDefaultProject()
    {
        Directory.CreateDirectory(DefaultProjectsRoot);
        var root = Path.Combine(DefaultProjectsRoot, "Field-TAK-Package");
        return EnsureProject(root, "Field-TAK-Package");
    }

    public ProjectLayout EnsureProject(string projectRoot, string? projectName = null)
    {
        projectRoot = Path.GetFullPath(projectRoot);
        Directory.CreateDirectory(projectRoot);
        var source = Path.Combine(projectRoot, "source");
        var output = Path.Combine(projectRoot, "out");
        EnsureSourceTree(source, output);
        EnsureProjectReadme(projectRoot, projectName ?? Path.GetFileName(projectRoot));

        var safeName = Slug(string.IsNullOrWhiteSpace(projectName) ? Path.GetFileName(projectRoot) : projectName!);
        var projectFile = Path.Combine(projectRoot, safeName + ".fthproj");
        return new ProjectLayout(projectRoot, source, output, projectFile);
    }

    private static void EnsureProjectReadme(string projectRoot, string projectName)
    {
        var readme = Path.Combine(projectRoot, "README.md");
        var generatedMarker = "Generated by Field TAK Hub Builder 2.3.0.";

        // Do not overwrite a README that the user has deliberately customized.
        // Refresh only READMEs previously generated by Builder.
        if (File.Exists(readme))
        {
            var existing = File.ReadAllText(readme);
            if (!existing.Contains("Generated by Field TAK Hub Builder", StringComparison.OrdinalIgnoreCase))
                return;
        }

        var text = "# " + projectName + "\n\n" +
            "Field TAK Hub 2.3.0 deployment project created by the Windows Builder.\n\n" +
            "## Aktualny workflow / Current workflow\n\n" +
            "1. Umieść dane wdrożenia w `source/`. / Put deployment files into `source/`.\n" +
            "2. Skonfiguruj dane pakietu, serwera, enrollment i opcjonalnie Meshtastic.\n" +
            "3. Uruchom **Analyze**, aby sprawdzić zawartość projektu.\n" +
            "4. Uruchom **Build Package**, aby zbudować podpisany pakiet `.ftak`.\n" +
            "5. Gotowy pakiet znajdziesz w `out/`.\n\n" +
            "## Source folders\n\n" +
            "- `atak/` — ATAK Mission Package i dane importowane przez ATAK\n" +
            "- `plugins/` — pluginy ATAK w formacie APK\n" +
            "- `maps/` — mapy i bazy map (MBTiles, GeoPackage, SQLite itd.)\n" +
            "- `overlays/` — nakładki KML/KMZ\n" +
            "- `config/` — dodatkowe pliki konfiguracyjne\n" +
            "- `data/` — inne dane deploymentu\n" +
            "- `meshtastic/` — opcjonalny `channel.url` i `profile.json`\n" +
            "- `enrollment/` — opcjonalny URI enrollmentu ATAK\n\n" +
            "## Meshtastic HYBRID\n\n" +
            "W Builderze możesz skonfigurować profil HYBRID, zgodny z architekturą Field TAK Hub. " +
            "Kanoniczny link kanału zaczynający się od `https://meshtastic.org/e/` trafia do " +
            "`source/meshtastic/channel.url`, a profil do `source/meshtastic/profile.json`.\n\n" +
            "Field TAK Hub przekazuje konfigurację. Obsługę radia BLE/USB wykonuje aplikacja/plugin Meshtastic.\n\n" +
            "## Enrollment\n\n" +
            "`source/enrollment/enroll.url` jest opcjonalny. Preferuj tokeny krótkotrwałe lub jednorazowe. " +
            "Nie publikuj URI zawierającego sekret razem z publicznym repozytorium lub paczką.\n\n" +
            "## Security\n\n" +
            "Nie umieszczaj w projekcie prywatnego klucza Publishera, haseł, danych MQTT ani stałych " +
            "danych logowania. Traktuj linki Meshtastic i URI enrollmentu jako dane wrażliwe.\n\n" +
            "Brakujące katalogi `source/` są automatycznie odtwarzane przez Builder.\n\n" +
            "> " + generatedMarker + "\n";
        File.WriteAllText(readme, text, new UTF8Encoding(false));
    }

    public void EnsureSourceTree(string sourceDirectory, string outputDirectory)
    {
        if (string.IsNullOrWhiteSpace(sourceDirectory) || string.IsNullOrWhiteSpace(outputDirectory))
        {
            var fallback = EnsureDefaultProject();
            sourceDirectory = string.IsNullOrWhiteSpace(sourceDirectory) ? fallback.SourceDirectory : sourceDirectory;
            outputDirectory = string.IsNullOrWhiteSpace(outputDirectory) ? fallback.OutputDirectory : outputDirectory;
        }

        sourceDirectory = Path.GetFullPath(sourceDirectory);
        outputDirectory = Path.GetFullPath(outputDirectory);
        Directory.CreateDirectory(sourceDirectory);
        Directory.CreateDirectory(outputDirectory);
        foreach (var folder in SourceFolders) Directory.CreateDirectory(Path.Combine(sourceDirectory, folder));

        var help = Path.Combine(sourceDirectory, "README-WRZUC-PLIKI-TUTAJ.txt");
        File.WriteAllText(help, HelpText, new UTF8Encoding(false));
    }

    public ProjectLayout CreateNewProject(string name)
    {
        Directory.CreateDirectory(DefaultProjectsRoot);
        var slug = Slug(name);
        var root = Path.Combine(DefaultProjectsRoot, slug);
        if (Directory.Exists(root) && Directory.EnumerateFileSystemEntries(root).Any())
        {
            var i = 2;
            string candidate;
            do candidate = Path.Combine(DefaultProjectsRoot, $"{slug}-{i++}");
            while (Directory.Exists(candidate));
            root = candidate;
        }
        return EnsureProject(root, name);
    }

    public static string FolderPath(string sourceDirectory, string folder)
    {
        if (!SourceFolders.Contains(folder, StringComparer.OrdinalIgnoreCase))
            throw new ArgumentOutOfRangeException(nameof(folder));
        return Path.Combine(sourceDirectory, folder.ToLowerInvariant());
    }

    public static string Slug(string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return "Field-TAK-Package";
        var chars = value.Trim().Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray();
        var slug = Regex.Replace(new string(chars), "-+", "-").Trim('-');
        return string.IsNullOrWhiteSpace(slug) ? "Field-TAK-Package" : slug;
    }

    private const string HelpText =
        "FIELD TAK HUB 2.3.0 — PROJECT SOURCE / ŹRÓDŁA PROJEKTU\n" +
        "============================================================\n" +
        "\n" +
        "PL:\n" +
        "Ten katalog jest źródłem danych dla Windows Buildera. Wrzucaj tutaj pliki,\n" +
        "a nie do katalogu out/. Builder analizuje source/ i podczas Build Package\n" +
        "tworzy podpisaną paczkę .ftak.\n" +
        "\n" +
        "FOLDERY:\n" +
        "atak\\         — ATAK Mission Package i dane importowane przez ATAK (.pref, KML/KMZ itd.)\n" +
        "plugins\\      — pluginy ATAK w formacie APK\n" +
        "maps\\         — mapy i bazy map (MBTiles, GeoPackage, SQLite itd.)\n" +
        "overlays\\     — nakładki KML/KMZ\n" +
        "config\\       — dodatkowe pliki konfiguracyjne\n" +
        "data\\         — inne dane deploymentu\n" +
        "meshtastic\\   — opcjonalny channel.url i profile.json\n" +
        "enrollment\\   — opcjonalny URI enrollmentu ATAK\n" +
        "\n" +
        "AKTUALNY WORKFLOW:\n" +
        "1. Otwórz projekt w Field TAK Hub Builder.\n" +
        "2. Umieść pliki w odpowiednich katalogach source/ lub przeciągnij je do Buildera.\n" +
        "3. Uzupełnij nazwę pakietu, Package ID, wersję i Publishera.\n" +
        "4. Skonfiguruj OpenTAKServer oraz porty, jeśli są potrzebne.\n" +
        "5. Opcjonalnie skonfiguruj ATAK Enrollment krótkotrwałym/jednorazowym URI.\n" +
        "6. Opcjonalnie skonfiguruj Meshtastic HYBRID.\n" +
        "7. Kliknij Analyze i sprawdź wynik walidacji.\n" +
        "8. Kliknij Build Package i zaakceptuj podgląd.\n" +
        "9. Gotowy podpisany plik .ftak znajdziesz w katalogu out/.\n" +
        "10. Do dystrybucji użyj dostępnych w Builderze opcji LAN, HTTPS/Cloud lub QR.\n" +
        "\n" +
        "MESHTASTIC - HYBRID:\n" +
        "1. Przygotuj konfigurację kanału Meshtastic.\n" +
        "2. Użyj kanonicznego linku zaczynającego się od:\n" +
        "   https://meshtastic.org/e/\n" +
        "3. W Builderze skonfiguruj profil Meshtastic i zapisz projekt.\n" +
        "4. Link kanału jest przechowywany jako source\\meshtastic\\channel.url.\n" +
        "5. Profil jest przechowywany jako source\\meshtastic\\profile.json.\n" +
        "6. W paczce .ftak dane trafiają do payload/meshtastic/.\n" +
        "\n" +
        "Field TAK Hub nie steruje bezpośrednio radiem Meshtastic. BLE/USB i komunikację\n" +
        "radiową obsługuje aplikacja/plugin Meshtastic. Hub przekazuje konfigurację wdrożenia.\n" +
        "\n" +
        "ENROLLMENT:\n" +
        "- source\\enrollment\\enroll.url jest opcjonalny.\n" +
        "- Preferuj token jednorazowy lub krótkotrwały.\n" +
        "- Nie publikuj URI enrollmentu zawierającego sekret w publicznym repozytorium.\n" +
        "\n" +
        "BEZPIECZEŃSTWO:\n" +
        "- NIE umieszczaj tutaj prywatnego klucza Publishera.\n" +
        "- NIE umieszczaj haseł, tokenów MQTT ani stałych danych logowania.\n" +
        "- Link Meshtastic może umożliwiać dostęp do chronionego kanału — traktuj go jako dane wrażliwe.\n" +
        "- Nie commituj zawartości source/ zawierającej sekrety.\n" +
        "- Podpis paczki .ftak jest wykonywany przez Buildera przy Build Package.\n" +
        "\n" +
        "SCHEMAT:\n" +
        "Projekt .fthproj korzysta ze schema version 2. Zawartość source/ jest pakowana\n" +
        "do formatu Field TAK Hub .ftak schema v2.\n" +
        "\n" +
        "Katalogi brakujące w source/ są automatycznie odtwarzane przez Builder.\n" +
        "\n" +
        "EN:\n" +
        "This directory is the data source for the Windows Builder. Put deployment files\n" +
        "here, not in out/. The Builder analyzes source/ and creates a signed .ftak package.\n" +
        "\n" +
        "FOLDERS:\n" +
        "atak\\         — ATAK Mission Package and ATAK-imported data (.pref, KML/KMZ, etc.)\n" +
        "plugins\\      — ATAK plugin APK files\n" +
        "maps\\         — maps and map databases (MBTiles, GeoPackage, SQLite, etc.)\n" +
        "overlays\\     — KML/KMZ overlays\n" +
        "config\\       — additional configuration files\n" +
        "data\\         — other deployment data\n" +
        "meshtastic\\   — optional channel.url and profile.json\n" +
        "enrollment\\   — optional ATAK enrollment URI\n" +
        "\n" +
        "BUILDER QUICK START:\n" +
        "1. Open the project in Field TAK Hub Builder.\n" +
        "2. Put files into the appropriate source/ folder or drag them into Builder.\n" +
        "3. Fill in package name, Package ID, version and Publisher.\n" +
        "4. Configure OpenTAKServer host and ports when needed.\n" +
        "5. Optionally configure a short-lived/one-time ATAK enrollment URI.\n" +
        "6. Optionally configure Meshtastic HYBRID.\n" +
        "7. Click Analyze.\n" +
        "8. Click Build Package and confirm the preview.\n" +
        "9. The signed .ftak package is written to out/.\n" +
        "10. Use the available LAN, HTTPS/Cloud or QR distribution options.\n" +
        "\n" +
        "MESHTASTIC - HYBRID:\n" +
        "- Use the canonical channel URL beginning with https://meshtastic.org/e/.\n" +
        "- Builder stores it in source\\meshtastic\\channel.url.\n" +
        "- Builder stores the profile in source\\meshtastic\\profile.json.\n" +
        "- Radio/BLE/USB I/O is handled by the Meshtastic application/plugin.\n" +
        "\n" +
        "SECURITY:\n" +
        "Do not store Publisher private keys, passwords, MQTT credentials or reusable secrets here.\n" +
        "Treat Meshtastic channel URLs and enrollment URIs as sensitive deployment information.\n" +
        "Missing source folders are automatically repaired by the Builder.\n";
}
