namespace FieldTakHub.Builder.Models;

public sealed class FieldTakManifest
{
    public string Schema { get; set; } = "fieldtak.package";
    public int SchemaVersion { get; set; } = 2;
    public PackageInfo Package { get; set; } = new();
    public TargetInfo Target { get; set; } = new();
    public ServerProfile Server { get; set; } = new();
    public EnrollmentProfile Enrollment { get; set; } = new();
    public MeshtasticProfile Meshtastic { get; set; } = new();
    public ComponentInfo Components { get; set; } = new();
    public SecurityInfo Security { get; set; } = new();
    public DistributionInfo Distribution { get; set; } = new();
    public PackageSizeInfo Size { get; set; } = new();
}

public sealed class PackageInfo
{
    public string Id { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Version { get; set; } = string.Empty;
    public string Description { get; set; } = "Generated by Field TAK Hub Builder 2.3.0";
    public DateTime CreatedUtc { get; set; }
    public string Publisher { get; set; } = string.Empty;
}
public sealed class TargetInfo
{
    public string Platform { get; set; } = "ATAK-CIV";
    public string MinVersion { get; set; } = string.Empty;
    public string MaxVersion { get; set; } = string.Empty;
}
public sealed class ComponentInfo
{
    public bool MissionPackage { get; set; }
    public int Plugins { get; set; }
    public int Files { get; set; }
    public bool Meshtastic { get; set; }
    public bool Enrollment { get; set; }
}
public sealed class SecurityInfo
{
    public string Hash { get; set; } = "SHA-256";
    public string Signature { get; set; } = "Ed25519";
    public string PublisherFingerprintSha256 { get; set; } = string.Empty;
}
public sealed class DistributionInfo
{
    public DateTime ExpiresUtc { get; set; }
    public int MaxDownloads { get; set; } = 50;
}

public sealed class PackageSizeInfo
{
    public long PayloadBytes { get; set; }
    public long UncompressedBytes { get; set; }
    public long RecommendedFreeBytes { get; set; }
}
